# Generated by Django 3.1.5 on 2021-01-12 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('cost', models.FloatField()),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], default='BUY', max_length=4)),
                ('count', models.FloatField()),
                ('total', models.FloatField()),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_stat.coin')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
    ]
