# Generated by Django 3.1.5 on 2021-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_stat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='coin_course',
            field=models.FloatField(default=0),
        ),
    ]
