# Generated by Django 3.1.5 on 2021-01-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_stat', '0002_deal_coin_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_deal', to='crypto_stat.coin'),
        ),
    ]
