# Generated by Django 3.1.5 on 2021-01-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_stat', '0003_auto_20210113_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinAveragePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_price', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_average_price', to='crypto_stat.coin')),
            ],
            options={
                'verbose_name': 'Coin Average Price',
                'verbose_name_plural': 'Coins Average Price',
            },
        ),
    ]
