# Generated by Django 3.1.5 on 2021-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_stat', '0004_coinaverageprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinaverageprice',
            name='coin_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinaverageprice',
            name='spend_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
