# Generated by Django 3.1.5 on 2021-01-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_stat', '0005_auto_20210115_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinAveragePrice',
        ),
    ]
