# Generated by Django 3.1.5 on 2021-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mono_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
