# Generated by Django 3.1.5 on 2021-01-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_client_mono_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='mono_token',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
